/**
 * ---------------------------------------------------------------------------------
 * This file has been generated by Sanity TypeGen.
 * Command: `sanity typegen generate`
 *
 * Any modifications made directly to this file will be overwritten the next time
 * the TypeScript definitions are generated. Please make changes to the Sanity
 * schema definitions and/or GROQ queries if you need to update these types.
 *
 * For more information on how to use Sanity TypeGen, visit the official documentation:
 * https://www.sanity.io/docs/sanity-typegen
 * ---------------------------------------------------------------------------------
 */

export declare const internalGroqTypeReferenceTo: unique symbol;

// Source: schema.json
export type SanityFileAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.fileAsset";
};

export type PolicyDocument = {
  _id: string;
  _type: "policyDocument";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  shortDescription?: string;
  file?: {
    asset?: SanityFileAssetReference;
    media?: unknown;
    _type: "file";
  };
  displayOrder?: number;
  lastReviewed?: string;
};

export type GalleryPhoto = {
  _id: string;
  _type: "galleryPhoto";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  internalTitle?: string;
  image?: ContentImage;
  category?:
    | "outdoor-learning-experience"
    | "indoor-learning-experience"
    | "language-immersion"
    | "nutrition-and-mealtimes"
    | "creative-play"
    | "sensory-exploration"
    | "nature-and-gardening"
    | "celebrations-and-community";
  showOnHomepage?: boolean;
  displayOrder?: number;
  showOnAboutPage?: boolean;
  aboutPageDisplayOrder?: number;
};

export type SanityImageAssetReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "sanity.imageAsset";
};

export type ContentImage = {
  _type: "contentImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  isDecorative?: boolean;
  altText?: string;
  caption?: string;
};

export type BusinessDetails = {
  _id: string;
  _type: "businessDetails";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  organizationName?: string;
  publicEmail?: string;
  primaryPhone?: {
    label?: string;
    number?: string;
  };
  secondaryPhone?: {
    label?: string;
    number?: string;
  };
  address?: {
    organisation?: string;
    line1?: string;
    line2?: string;
    city?: string;
    postcode?: string;
    shortLocation?: string;
    mapUrl?: string;
  };
  openingDays?: string;
  openingTime?: string;
  closingTime?: string;
  morningSessionEnd?: string;
  afternoonSessionStart?: string;
  weeksOpen?: number;
  minimumAttendanceDays?: number;
  ageRange?: {
    minimum?: number;
    maximum?: number;
    displayOverride?: string;
  };
  languages?: Array<string>;
  social?: {
    facebookUrl?: string;
    instagramUrl?: string;
  };
  availabilityMessage?: string;
  footerBusinessCopy?: string;
  footerTagline?: {
    prefix?: string;
    purplePhrase?: string;
    separatorOne?: string;
    greenPhrase?: string;
    connector?: string;
    bluePhrase?: string;
    suffix?: string;
  };
};

export type HomePageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "homePage";
};

export type AboutPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "aboutPage";
};

export type MultilingualPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "multilingualPage";
};

export type HoursNutritionPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "hoursNutritionPage";
};

export type ParentsPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "parentsPage";
};

export type GalleryPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "galleryPage";
};

export type ContactPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "contactPage";
};

export type ThankYouPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "thankYouPage";
};

export type BlogPageReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPage";
};

export type BlogPostReference = {
  _ref: string;
  _type: "reference";
  _weak?: boolean;
  [internalGroqTypeReferenceTo]?: "blogPost";
};

export type BlogPortableText = Array<
  | {
      children?: Array<{
        marks?: Array<string>;
        text?: string;
        _type: "span";
        _key: string;
      }>;
      style?: "normal" | "h2" | "h3";
      listItem?: "bullet" | "number";
      markDefs?: Array<
        | {
            href?: string;
            _type: "link";
            _key: string;
          }
        | {
            reference?:
              | HomePageReference
              | AboutPageReference
              | MultilingualPageReference
              | HoursNutritionPageReference
              | ParentsPageReference
              | GalleryPageReference
              | ContactPageReference
              | ThankYouPageReference
              | BlogPageReference
              | BlogPostReference;
            _type: "internalLink";
            _key: string;
          }
      >;
      level?: number;
      _type: "block";
      _key: string;
    }
  | ({
      _key: string;
    } & ContentImage)
>;

export type BlogPost = {
  _id: string;
  _type: "blogPost";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  title?: string;
  slug?: Slug;
  publishedAt?: string;
  featured?: boolean;
  category?:
    | "nursery-news"
    | "early-learning"
    | "parenting-tips"
    | "nutrition"
    | "community";
  excerpt?: string;
  featuredImage?: StrictImage;
  body?: BlogPortableText;
};

export type StrictImage = {
  _type: "strictImage";
  asset?: SanityImageAssetReference;
  media?: unknown;
  hotspot?: SanityImageHotspot;
  crop?: SanityImageCrop;
  altText?: string;
  caption?: string;
};

export type Slug = {
  _type: "slug";
  current?: string;
  source?: string;
};

export type BlogPage = {
  _id: string;
  _type: "blogPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitleLineOne?: string;
  heroTitleLineTwo?: string;
  heroParagraphs?: PagePortableText;
  latestArticlesEyebrow?: string;
  latestArticlesHeading?: string;
  latestArticlesIntroduction?: PagePortableText;
};

export type PagePortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: "bullet" | "number";
  markDefs?: Array<{
    href?: string;
    _type: "link";
    _key: string;
  }>;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type ThankYouPage = {
  _id: string;
  _type: "thankYouPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitleLineOne?: string;
  heroTitleLineTwo?: string;
  heroParagraphs?: PagePortableText;
  primaryCtaLabel?: string;
  secondaryCtaLabel?: string;
  nextStepsEyebrow?: string;
  nextStepsHeading?: string;
  nextStepsBody?: PagePortableText;
};

export type ContactPage = {
  _id: string;
  _type: "contactPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitleLineOne?: string;
  heroTitleLineTwo?: string;
  heroParagraphs?: PagePortableText;
  enquiryPanelTitle?: string;
  formIntro?: string;
  enquiryPanelCtaLabel?: string;
  nextStepsLabel?: string;
  nextStepsHeading?: string;
  nextStepsParagraphs?: PagePortableText;
  stepOne?: {
    title?: string;
    description?: string;
  };
  stepTwo?: {
    title?: string;
    description?: string;
  };
  stepThree?: {
    title?: string;
    description?: string;
  };
  stepFour?: {
    title?: string;
    description?: string;
  };
  locationLabel?: string;
  locationHeading?: string;
};

export type GalleryPage = {
  _id: string;
  _type: "galleryPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitleLineOne?: string;
  heroTitleLineTwo?: string;
  heroParagraphs?: PagePortableText;
  heroCtaLabel?: string;
  galleryIntroLabel?: string;
  galleryIntroHeading?: string;
  galleryIntroCopy?: PagePortableText;
  finalCtaHeading?: string;
  finalCtaCopy?: PagePortableText;
  finalCtaLabel?: string;
};

export type ParentsPage = {
  _id: string;
  _type: "parentsPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitleLineOne?: string;
  heroTitleLineTwo?: string;
  heroParagraphs?: PagePortableText;
  startingSchoolLabel?: string;
  startingSchoolHeading?: string;
  startingSchoolParagraphs?: PagePortableText;
  schoolSupport?: Array<string>;
  feesFundingLabel?: string;
  feesFundingHeading?: string;
  feesFundingParagraphs?: PagePortableText;
  howFundingWorksLabel?: string;
  howFundingWorksHeading?: string;
  howFundingWorksParagraphs?: PagePortableText;
  fundingExamples?: Array<{
    entitlement?: string;
    equivalent?: string;
    _key: string;
  }>;
  fundingSupportLabel?: string;
  fundingSupportHeading?: string;
  fundingSupportParagraphs?: PagePortableText;
  taxFreeLabel?: string;
  taxFreeHeading?: string;
  taxFreeParagraphs?: PagePortableText;
  weeklyFeesLabel?: string;
  weeklyFeesHeading?: string;
  weeklyFeesParagraphs?: PagePortableText;
  fullDayRate?: string;
  halfDayRate?: string;
  fundedHourDeductions?: string;
  additionalCharges?: string;
  exampleWeeklyCosts?: string;
  subsidyFaqsLabel?: string;
  subsidyFaqsHeading?: string;
  subsidyFaqsParagraphs?: PagePortableText;
  subsidyFaqs?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  partnershipLabel?: string;
  partnershipHeading?: string;
  partnershipParagraphs?: PagePortableText;
  settlingInLabel?: string;
  settlingInHeading?: string;
  settlingInParagraphs?: PagePortableText;
  partnershipText?: string;
  settlingStrategies?: Array<string>;
  policiesHeading?: string;
  policiesIntro?: PagePortableText;
  policiesSupportingNote?: string;
};

export type HoursNutritionPage = {
  _id: string;
  _type: "hoursNutritionPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitleLineOne?: string;
  heroTitleLineTwo?: string;
  heroParagraphs?: PagePortableText;
  operatingHoursLabel?: string;
  operatingHoursHeading?: string;
  operatingHoursParagraphs?: PagePortableText;
  minAttendancePanelTitle?: string;
  minAttendancePanelCopy?: string;
  nutritionLabel?: string;
  nutritionHeading?: string;
  nutritionParagraphs?: PagePortableText;
  nutritionChecklist?: Array<string>;
  freshlyPreparedHeading?: string;
  chefNote?: string;
  typicalDayLabel?: string;
  typicalDayHeading?: string;
  typicalDayLead?: string;
  welcomeAndFreePlay?: {
    startTime?: string;
    endTime?: string;
    title?: string;
    description?: string;
  };
  learningAndExploration?: {
    startTime?: string;
    endTime?: string;
    title?: string;
    description?: string;
  };
  morningSnack?: {
    startTime?: string;
    endTime?: string;
    title?: string;
    description?: string;
  };
  outdoorAdventures?: {
    startTime?: string;
    endTime?: string;
    title?: string;
    description?: string;
  };
  lunch?: {
    startTime?: string;
    endTime?: string;
    title?: string;
    description?: string;
  };
  restAndQuietTime?: {
    startTime?: string;
    endTime?: string;
    title?: string;
    description?: string;
  };
  afternoonPlayAndHome?: {
    startTime?: string;
    endTime?: string;
    title?: string;
    description?: string;
  };
  contactPanelTitle?: string;
  contactPanelCopy?: string;
  contactPanelCtaLabel?: string;
};

export type MultilingualPage = {
  _id: string;
  _type: "multilingualPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitleLineOne?: string;
  heroTitleLineTwo?: string;
  heroParagraphs?: PagePortableText;
  philosophyLabel?: string;
  philosophyHeading?: string;
  philosophyParagraphs?: PagePortableText;
  childrenEnjoyHeading?: string;
  philosophyPoints?: Array<string>;
  languageConnectionLabel?: string;
  languageConnectionHeading?: string;
  languageConnectionParagraphs?: PagePortableText;
  languageConnectionImage?: ContentImage;
  eyfsLabel?: string;
  eyfsHeading?: string;
  eyfsParagraphs?: PagePortableText;
  eyfsCommunication?: {
    title?: string;
    description?: string;
  };
  eyfsPhysical?: {
    title?: string;
    description?: string;
  };
  eyfsPersonal?: {
    title?: string;
    description?: string;
  };
  eyfsLiteracy?: {
    title?: string;
    description?: string;
  };
  eyfsMaths?: {
    title?: string;
    description?: string;
  };
  eyfsUnderstanding?: {
    title?: string;
    description?: string;
  };
  eyfsArts?: {
    title?: string;
    description?: string;
  };
  screenFreeLabel?: string;
  screenFreeHeading?: string;
  screenFreeParagraphs?: PagePortableText;
  screenFreeBenefits?: Array<string>;
  closingNote?: string;
};

export type AboutPage = {
  _id: string;
  _type: "aboutPage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitleLineOne?: string;
  heroTitleLineTwo?: string;
  heroParagraphs?: PagePortableText;
  approachLabel?: string;
  approachHeading?: string;
  approachParagraphs?: PagePortableText;
  approachChildLed?: {
    title?: string;
    description?: string;
  };
  approachCalmRhythm?: {
    title?: string;
    description?: string;
  };
  approachLearning?: {
    title?: string;
    description?: string;
  };
  approachExploration?: {
    title?: string;
    description?: string;
  };
  approachConfidence?: {
    title?: string;
    description?: string;
  };
  approachRelationships?: {
    title?: string;
    description?: string;
  };
  commitmentLabel?: string;
  commitmentHeading?: string;
  commitmentParagraphs?: PagePortableText;
  commitmentImage?: ContentImage;
  environmentLabel?: string;
  environmentHeading?: string;
  environmentParagraphs?: PagePortableText;
  environmentImage?: ContentImage;
  programmesLabel?: string;
  programmesHeading?: string;
  programmesParagraphs?: PagePortableText;
  foundationCommunication?: string;
  foundationEmpathy?: string;
  foundationIndependence?: string;
  foundationCreativity?: string;
  foundationCriticalThinking?: string;
  educatorsLabel?: string;
  educatorsHeading?: string;
  educatorsParagraphs?: PagePortableText;
  educatorsImage?: ContentImage;
  leadershipLabel?: string;
  leadershipHeading?: string;
  leadershipParagraphs?: PagePortableText;
  leadershipImage?: ContentImage;
  team?: Array<{
    name?: string;
    role?: string;
    bio?: string;
    _key: string;
  }>;
  gallerySectionLabel?: string;
  gallerySectionHeading?: string;
};

export type HomePage = {
  _id: string;
  _type: "homePage";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  heroEyebrow?: string;
  heroTitleLineOne?: string;
  heroTitleLineTwo?: string;
  heroSubtitle?: string;
  heroParagraphs?: PagePortableText;
  primaryCtaLabel?: string;
  secondaryCtaLabel?: string;
  multilingualFeature?: {
    title?: string;
    description?: string;
  };
  childCentredFeature?: {
    title?: string;
    description?: string;
  };
  playToLearnFeature?: {
    title?: string;
    description?: string;
  };
  valuesIntroHeading?: {
    prefix?: string;
    purplePhrase?: string;
    connector?: string;
    bluePhrase?: string;
  };
  valuesIntroParagraphs?: PagePortableText;
  valuesDifferenceTitle?: string;
  screenFreeCard?: {
    title?: string;
    description?: string;
  };
  multilingualCard?: {
    title?: string;
    description?: string;
  };
  indoorOutdoorCard?: {
    title?: string;
    description?: string;
  };
  childLedCard?: {
    title?: string;
    description?: string;
  };
  nutritionCard?: {
    title?: string;
    description?: string;
  };
  familySettingCard?: {
    title?: string;
    description?: string;
  };
  visitTitleLineOne?: string;
  visitTitleLineTwo?: string;
  visitParagraphs?: PagePortableText;
  visitCtaLabel?: string;
  visitImage?: ContentImage;
  testimonialQuote?: string;
  testimonialAttribution?: string;
  faqTitleLineOne?: string;
  faqTitleLineTwo?: string;
  faqIntro?: string;
  faqs?: Array<{
    question?: string;
    answer?: string;
    _key: string;
  }>;
  helpPanelTitle?: string;
  helpPanelCopy?: string;
  helpPanelCtaLabel?: string;
  galleryIntroTitle?: string;
  galleryIntro?: string;
};

export type MinimalPortableText = Array<{
  children?: Array<{
    marks?: Array<string>;
    text?: string;
    _type: "span";
    _key: string;
  }>;
  style?: "normal";
  listItem?: never;
  markDefs?: null;
  level?: number;
  _type: "block";
  _key: string;
}>;

export type SanityImageCrop = {
  _type: "sanity.imageCrop";
  top?: number;
  bottom?: number;
  left?: number;
  right?: number;
};

export type SanityImageHotspot = {
  _type: "sanity.imageHotspot";
  x?: number;
  y?: number;
  height?: number;
  width?: number;
};

export type SanityImagePaletteSwatch = {
  _type: "sanity.imagePaletteSwatch";
  background?: string;
  foreground?: string;
  population?: number;
  title?: string;
};

export type SanityImagePalette = {
  _type: "sanity.imagePalette";
  darkMuted?: SanityImagePaletteSwatch;
  lightVibrant?: SanityImagePaletteSwatch;
  darkVibrant?: SanityImagePaletteSwatch;
  vibrant?: SanityImagePaletteSwatch;
  dominant?: SanityImagePaletteSwatch;
  lightMuted?: SanityImagePaletteSwatch;
  muted?: SanityImagePaletteSwatch;
};

export type SanityImageDimensions = {
  _type: "sanity.imageDimensions";
  height?: number;
  width?: number;
  aspectRatio?: number;
};

export type SanityImageMetadata = {
  _type: "sanity.imageMetadata";
  location?: Geopoint;
  dimensions?: SanityImageDimensions;
  palette?: SanityImagePalette;
  lqip?: string;
  blurHash?: string;
  thumbHash?: string;
  hasAlpha?: boolean;
  isOpaque?: boolean;
};

export type SanityFileAsset = {
  _id: string;
  _type: "sanity.fileAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  source?: SanityAssetSourceData;
};

export type SanityAssetSourceData = {
  _type: "sanity.assetSourceData";
  name?: string;
  id?: string;
  url?: string;
};

export type SanityImageAsset = {
  _id: string;
  _type: "sanity.imageAsset";
  _createdAt: string;
  _updatedAt: string;
  _rev: string;
  originalFilename?: string;
  label?: string;
  title?: string;
  description?: string;
  altText?: string;
  sha1hash?: string;
  extension?: string;
  mimeType?: string;
  size?: number;
  assetId?: string;
  uploadId?: string;
  path?: string;
  url?: string;
  metadata?: SanityImageMetadata;
  source?: SanityAssetSourceData;
};

export type Geopoint = {
  _type: "geopoint";
  lat?: number;
  lng?: number;
  alt?: number;
};

export type AllSanitySchemaTypes =
  | SanityFileAssetReference
  | PolicyDocument
  | GalleryPhoto
  | SanityImageAssetReference
  | ContentImage
  | BusinessDetails
  | HomePageReference
  | AboutPageReference
  | MultilingualPageReference
  | HoursNutritionPageReference
  | ParentsPageReference
  | GalleryPageReference
  | ContactPageReference
  | ThankYouPageReference
  | BlogPageReference
  | BlogPostReference
  | BlogPortableText
  | BlogPost
  | StrictImage
  | Slug
  | BlogPage
  | PagePortableText
  | ThankYouPage
  | ContactPage
  | GalleryPage
  | ParentsPage
  | HoursNutritionPage
  | MultilingualPage
  | AboutPage
  | HomePage
  | MinimalPortableText
  | SanityImageCrop
  | SanityImageHotspot
  | SanityImagePaletteSwatch
  | SanityImagePalette
  | SanityImageDimensions
  | SanityImageMetadata
  | SanityFileAsset
  | SanityAssetSourceData
  | SanityImageAsset
  | Geopoint;
