import { defineType, defineField } from "sanity";

export const galleryPage = defineType({
  name: "galleryPage",
  title: "Gallery Page",
  type: "document",
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Hero Eyebrow",
      description: "Optional small text above title.",
      type: "string",
      validation: (rule) => rule.max(30),
    }),
    defineField({
      name: "heroTitleLineOne",
      title: "Hero Title - Line One",
      description: "First line of main heading.",
      type: "string",
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: "heroTitleLineTwo",
      title: "Hero Title - Line Two",
      description: "Second line of main heading.",
      type: "string",
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: "heroParagraphs",
      title: "Hero Paragraphs",
      description: "Main introductory paragraphs.",
      type: "pagePortableText",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "heroCtaLabel",
      title: "Hero CTA Label",
      description: "Label for the hero CTA button.",
      type: "string",
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: "galleryIntroLabel",
      title: "Gallery Intro Label",
      description: "Eyebrow for the gallery grid section.",
      type: "string",
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: "galleryIntroHeading",
      title: "Gallery Intro Heading",
      description: "Heading for the gallery grid section.",
      type: "string",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "galleryIntroCopy",
      title: "Gallery Intro Copy",
      description: "Paragraph for the gallery grid section.",
      type: "pagePortableText",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "finalCtaHeading",
      title: "Final CTA Heading",
      description: "Heading for the final call to action.",
      type: "string",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "finalCtaCopy",
      title: "Final CTA Copy",
      description: "Text for the final call to action.",
      type: "pagePortableText",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "finalCtaLabel",
      title: "Final CTA Label",
      description: "Label for the final CTA button.",
      type: "string",
      validation: (rule) => rule.required().max(40),
    }),
  ],
});
