import { defineType, defineField } from "sanity";

export const multilingualPage = defineType({
  name: "multilingualPage",
  title: "Multilingual Page",
  type: "document",
  groups: [
    { name: "hero", title: "Hero" },
    { name: "philosophy", title: "Philosophy" },
    { name: "languageConnection", title: "Language & Connection" },
    { name: "eyfs", title: "EYFS" },
    { name: "screenFree", title: "Screen-Free" },
  ],
  fields: [
    defineField({
      name: "heroEyebrow",
      title: "Hero Eyebrow",
      description: "Optional small text above title.",
      type: "string",
      group: "hero",
      validation: (rule) => rule.max(30),
    }),
    defineField({
      name: "heroTitleLineOne",
      title: "Hero Title - Line One",
      description: "First line of main heading.",
      type: "string",
      group: "hero",
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: "heroTitleLineTwo",
      title: "Hero Title - Line Two",
      description: "Second line of main heading.",
      type: "string",
      group: "hero",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "heroParagraphs",
      title: "Hero Paragraphs",
      description: "Main introductory paragraphs.",
      type: "pagePortableText",
      group: "hero",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "philosophyHeading",
      title: "Philosophy Section Heading",
      description: "The main H2 heading.",
      type: "string",
      group: "philosophy",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "philosophyParagraphs",
      title: "Philosophy Paragraphs",
      description: "Text for this section.",
      type: "pagePortableText",
      group: "philosophy",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "childrenEnjoyHeading",
      title: "Children Enjoy Heading",
      description: "Heading for the activity list.",
      type: "string",
      group: "philosophy",
      validation: (rule) => rule.required().max(60),
    }),
    defineField({
      name: "philosophyPoints",
      title: "Philosophy Points",
      description:
        "List of experiences children enjoy. Must be exactly 6 items.",
      type: "array",
      group: "philosophy",
      of: [{ type: "string", validation: (rule) => rule.required().max(120) }],
      validation: (rule) =>
        rule.required().length(6).error("Must be exactly 6 items."),
    }),
    defineField({
      name: "languageConnectionHeading",
      title: "Language Connection Section Heading",
      description: "The main H2 heading.",
      type: "string",
      group: "languageConnection",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "languageConnectionParagraphs",
      title: "Language Connection Paragraphs",
      description: "Text for this section.",
      type: "pagePortableText",
      group: "languageConnection",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "eyfsLabel",
      title: "EYFS Section Label",
      description: "The eyebrow label.",
      type: "string",
      group: "eyfs",
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: "eyfsHeading",
      title: "EYFS Section Heading",
      description: "The main H2 heading.",
      type: "string",
      group: "eyfs",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "eyfsParagraphs",
      title: "EYFS Introductory Paragraphs",
      description: "Introductory text displayed before the seven areas.",
      type: "pagePortableText",
      group: "eyfs",
      validation: (rule) => rule.required(),
    }),
    ...[
      "eyfsCommunication",
      "eyfsPhysical",
      "eyfsPersonal",
      "eyfsLiteracy",
      "eyfsMaths",
      "eyfsUnderstanding",
      "eyfsArts",
    ].map((slot) =>
      defineField({
        name: slot,
        title: `${slot.replace(/eyfs([A-Z])/g, "EYFS $1").replace(/^./, (str) => str.toUpperCase())}`,
        description: `Fixed EYFS slot for ${slot}.`,
        type: "object",
        group: "eyfs",
        fields: [
          defineField({
            name: "title",
            type: "string",
            title: "Title",
            validation: (rule) => rule.required().max(60),
          }),
          defineField({
            name: "description",
            type: "text",
            title: "Description",
            validation: (rule) => rule.max(150),
          }),
        ],
        validation: (rule) => rule.required(),
      }),
    ),
    defineField({
      name: "screenFreeLabel",
      title: "Screen-Free Section Label",
      description: "The eyebrow label.",
      type: "string",
      group: "screenFree",
      validation: (rule) => rule.required().max(40),
    }),
    defineField({
      name: "screenFreeHeading",
      title: "Screen-Free Section Heading",
      description: "The main H2 heading.",
      type: "string",
      group: "screenFree",
      validation: (rule) => rule.required().max(80),
    }),
    defineField({
      name: "screenFreeParagraphs",
      title: "Screen-Free Paragraphs",
      description: "Text for this section.",
      type: "pagePortableText",
      group: "screenFree",
      validation: (rule) => rule.required(),
    }),
    defineField({
      name: "screenFreeBenefitsHeading",
      title: "Screen-Free Benefits Heading",
      description: "Heading shown above the benefits list.",
      type: "string",
      group: "screenFree",
      validation: (rule) => rule.required().max(60),
    }),
    defineField({
      name: "screenFreeBenefits",
      title: "Screen-Free Benefits",
      description:
        "List of benefits. Must be exactly 5 items based on the visual design.",
      type: "array",
      group: "screenFree",
      of: [{ type: "string", validation: (rule) => rule.required().max(120) }],
      validation: (rule) =>
        rule.required().length(5).error("Must be exactly 5 items."),
    }),
    defineField({
      name: "closingNote",
      title: "Closing Note",
      description: "Final statement at the bottom of the screen-free section.",
      type: "string",
      group: "screenFree",
      validation: (rule) => rule.required().max(240),
    }),
  ],
});
